# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-23.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
conda:
  environment: ci/doc.yml

formats: []
