name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        os: [ubuntu-24.04]

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # Install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies from requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
          python -m pip install .

      # Run the unit tests
      - name: Test with pytest
        run: |
          pytest --verbose cupy_xarray/tests/
